<!--  Copyright (c) 0x5BFA. Licensed under the MIT License.  -->
<Project>
	<PropertyGroup>

		<!--  General properties  -->
		<TargetWindowsVersion>10.0.26100.0</TargetWindowsVersion>
		<RootNamespace>DesktopFlyouts</RootNamespace>
		<DefaultLanguage>en-US</DefaultLanguage>
		<!--<TreatWarningsAsErrors>true</TreatWarningsAsErrors>-->

	</PropertyGroup>
</Project>
