<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>

        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0-windows$(TargetWindowsVersion)</TargetFramework>
        <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
        <PublishProfile>win-$(Platform).pubxml</PublishProfile>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <EnableMsixTooling>true</EnableMsixTooling>

        <DefineConstants>$(DefineConstants);DISABLE_XAML_GENERATED_MAIN</DefineConstants>

        <UseUwp>true</UseUwp>
        <UseUwpTools>true</UseUwpTools>
        <DisableEmbeddedXbf>false</DisableEmbeddedXbf>

    </PropertyGroup>

    <ItemGroup>
        <AppxTargetDeviceFamilyItem Include="Windows.Desktop" />
        <Manifest Include="$(ApplicationManifest)" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="Assets\**" />
        <Content Include="Tray.ico" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.UI.Xaml" />
        <PackageReference Include="Microsoft.Windows.CsWinRT" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\DesktopFlyouts.Uwp\DesktopFlyouts.Uwp.csproj" />
    </ItemGroup>

</Project>
