<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <NuGetPackageRoot Condition="'$(NuGetPackageRoot)' == ''">$(UserProfile)\.nuget\packages\</NuGetPackageRoot>
    <CppWinRTVersion Condition="'$(CppWinRTVersion)' == ''">3.0.260818.1</CppWinRTVersion>
    <CppWinRTPackageRoot Condition="'$(CppWinRTPackageRoot)' == ''">$(NuGetPackageRoot)microsoft.windows.cppwinrt\$(CppWinRTVersion)</CppWinRTPackageRoot>
  </PropertyGroup>
</Project>
