<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<WindowsSdkReferenceVersion>10.0.26100.0</WindowsSdkReferenceVersion>
		<TargetFramework>net10.0-windows$(WindowsSdkReferenceVersion)</TargetFramework>
		<Platforms>x64;arm64</Platforms>
		<PlatformTarget>AnyCPU</PlatformTarget>
		<UseUwp>true</UseUwp>
		<DefaultLanguage>en-US</DefaultLanguage>
		<CsWinRTIncludes>DesktopFlyouts</CsWinRTIncludes>
		<NoWarn>$(NoWarn);CS0108;CS0436</NoWarn>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<PackageId>DesktopFlyouts.Uwp</PackageId>
		<Authors>0x5BFA</Authors>
		<Description>UWP projection and native runtime for DesktopFlyouts.</Description>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageProjectUrl>https://github.com/0x5bfa/DesktopFlyouts</PackageProjectUrl>
		<RepositoryUrl>https://github.com/0x5bfa/DesktopFlyouts</RepositoryUrl>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageTags>UWP WinRT flyout</PackageTags>
		<DebugType>embedded</DebugType>
		<Deterministic>true</Deterministic>
		<EmbedUntrackedSources>true</EmbedUntrackedSources>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Windows.CsWinRT" Version="2.3.1" />
		<PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.401" PrivateAssets="all" />
		<CsWinRTInputs Include="$(MSBuildProjectDirectory)/../../$(Platform)/$(Configuration)/DesktopFlyouts.Uwp/DesktopFlyouts.winmd" />
		<CsWinRTInputs Include="$(MSBuildProgramFiles32)/Windows Kits/10/References/$(WindowsSdkReferenceVersion)/Windows.Foundation.UniversalApiContract/19.0.0.0/Windows.Foundation.UniversalApiContract.winmd" />
		<CsWinRTInputs Include="$(MSBuildProgramFiles32)/Windows Kits/10/References/$(WindowsSdkReferenceVersion)/Windows.UI.Xaml.Hosting.HostingContract/5.0.0.0/Windows.UI.Xaml.Hosting.HostingContract.winmd" />
		<None Include="$(MSBuildProjectDirectory)/../../README.md" Pack="true" PackagePath="/" />
		<None Include="$(MSBuildProjectDirectory)/../../LICENSE" Pack="true" PackagePath="/" />
		<None Include="$(MSBuildProjectDirectory)/../../x64/Release/DesktopFlyouts.Uwp/DesktopFlyouts.Uwp.dll" Pack="true" PackagePath="runtimes/win-x64/native/" />
		<None Include="$(MSBuildProjectDirectory)/../../ARM64/Release/DesktopFlyouts.Uwp/DesktopFlyouts.Uwp.dll" Pack="true" PackagePath="runtimes/win-arm64/native/" />
	</ItemGroup>

</Project>
