# Copyright (c) 0x5BFA. All rights reserved.
# Licensed under the MIT license.

name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'

run-name: ${{ github.event_name == 'pull_request' && 'PR validation' || 'CI validation' }}

env:
  SOLUTION_PATH: 'DesktopFlyouts.slnx'

jobs:
  build:
    runs-on: windows-2025-vs2026
    strategy:
      fail-fast: false
      matrix:
        configuration: [Debug, Release]
    env:
      CONFIGURATION: ${{ matrix.configuration }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v3
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v4

    - name: Build solution
      run: msbuild /restore $env:SOLUTION_PATH /t:Build /p:Configuration=$env:CONFIGURATION /p:Platform=x64 /m
